package improved;

public enum EventActions {
	SWITCH_FAN_ON_TRANSITION,
	SWITCH_FAN_OFF_TRANSITION,
	SET_HEATER_MODE_ACTIVE_TRANSITION,
	SET_AC_MODE_ACTIVE_TRANSITION,
	SWITCH_HEATER_ON_WHEN_HEATER_ENABLED_TRANSITION,
	SWITCH_HEATER_OFF_WHEN_HEATER_ENABLED_TRANSITION,
	SWITCH_AC_ON_WHEN_AC_ENABLED_TRANSITION,
	SWITCH_AC_OFF_WHEN_AC_ENABLED_TRANSITION,
	DO_NOTHING_TRANSITION

}
